spring.application.name=patient-service

server.port=4000

logging.level.root=info

billing.service.address=${BILLING_SERVICE_ADDRESS:billing-service}

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.ByteArraySerializer

jwkSetUri=http://auth-service:4005/.well-known/jwks.json

logging.level.org.springframework.security=DEBUG
